name: CI/CD for deploy

on:
  push:
    branches:
      - main

jobs:
  CI-CD-DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node.js
        uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Install
        run: npm install
      
      - name: Deploy
        run: npm run deploy

        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}